# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9xxAwuP-5i0PrTBCe-yCL17zSdyqBgv
"""

from flask import Flask, render_template, request
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import os

app = Flask(__name__)
model = load_model('models/brain_tumor_model.h5')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    img = request.files['file']
    img_path = os.path.join('static', img.filename)
    img.save(img_path)

    img_loaded = image.load_img(img_path, target_size=(150, 150))
    img_array = image.img_to_array(img_loaded) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    result = 'Tumor' if np.argmax(prediction) == 1 else 'No Tumor'

    return render_template('index.html', prediction=result, image_path=img_path)

if __name__ == "__main__":
    app.run(debug=True)